package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, November 3, 2025 11:08:25 AM WAT
*/


// Interface du service bancaire
public interface IBanqueRemoteOperations 
{

  // creer un nouveau compte
  void creerCompte (corbaBanque.Compte cpte);

  // deposer de l'argent
  void verser (float mt, int code);

  // retirer de l'argent
  void retirer (float mt, int code);

  // recuperer un compte par son code
  corbaBanque.Compte getCompte (int code);

  // recuperer tous les comptes
  corbaBanque.Compte[] getComptes ();

  // convertir euro vers dinar
  double conversion (float mt);
} // interface IBanqueRemoteOperations
